
INSERT INTO POSITIONS (UPDATE_COUNTER,POSITION)
VALUES (0,'Cashier');

INSERT INTO POSITIONS (UPDATE_COUNTER,POSITION)
VALUES (0,'Manager');

INSERT INTO POSITIONS (UPDATE_COUNTER,POSITION)
VALUES (0,'Security');

INSERT INTO EMPLOYEES 
     VALUES (0,'MIROSLAV','Address 1',(SELECT ID FROM POSITIONS WHERE POSITION='Security'));

INSERT INTO EMPLOYEES 
     VALUES (0,'Caren','Address 2',(SELECT ID FROM POSITIONS WHERE POSITION='Cashier'));

INSERT INTO EMPLOYEES 
     VALUES (0,'Stoqn','Address 4',(SELECT ID FROM POSITIONS WHERE POSITION='Manager'));