
CREATE TABLE POSITIONS
(
ID INT IDENTITY(1,1) CONSTRAINT PK_POSITIONS_ID PRIMARY KEY NOT NULL,
UPDATE_COUNTER INT NOT NULL,
POSITION NVARCHAR(32) NOT NULL,
)

CREATE TABLE EMPLOYEES 
(
ID INT IDENTITY(1,1) CONSTRAINT PK_EMPLOYEES_ID PRIMARY KEY NOT NULL,
UPDATE_COUNTER INT NOT NULL,
NAME NVARCHAR(32) NOT NULL,
ADDRESS NVARCHAR(128) NOT NULL,
POSITION_ID INT NOT NULL
)

ALTER TABLE EMPLOYEES 
   ADD CONSTRAINT FK_EMPLOYEES_POSITIONS_ID FOREIGN KEY (POSITION_ID)
      REFERENCES POSITIONS (ID)
;