DROP TABLE IF EXISTS dbo.Warehouse_Contracts;
DROP TABLE IF EXISTS dbo.Warehouse_Rooms;
DROP TABLE IF EXISTS dbo.Warehouses;
DROP TABLE IF EXISTS dbo.Admin_Accounts;
DROP TABLE IF EXISTS dbo.Owner_Accounts;
DROP TABLE IF EXISTS dbo.Agent_Accounts;
DROP TABLE IF EXISTS dbo.Owners;
DROP TABLE IF EXISTS dbo.Admins;
DROP TABLE IF EXISTS dbo.Agents;
DROP TABLE IF EXISTS dbo.Warehouse_Status;
DROP TABLE IF EXISTS dbo.Warehouse_Types;
DROP TABLE IF EXISTS dbo.Climate_Conditions;
DROP TABLE IF EXISTS dbo.Renter;


GO

CREATE TABLE Admins (
	ID int IDENTITY(1, 1) NOT NULL, CONSTRAINT PK_ADMINS_ID PRIMARY KEY CLUSTERED (ID),
	FirstName nvarchar(50) NOT NULL,
	LastName nvarchar(50) NOT NULL
	);

GO

CREATE TABLE Owners (
	ID int IDENTITY(1, 1) NOT NULL, CONSTRAINT PK_OWNERS_ID PRIMARY KEY CLUSTERED (ID),
	FirstName nvarchar(50) NOT NULL,
	LastName nvarchar(50) NOT NULL
	);

GO

CREATE TABLE Agents (
	ID int IDENTITY(1, 1) NOT NULL, CONSTRAINT PK_AGENTS_ID PRIMARY KEY CLUSTERED (ID),
	FirstName nvarchar(50) NOT NULL,
	LastName nvarchar(50) NOT NULL,
	Raiting float NOT NULL
	);

GO


CREATE TABLE Admin_Accounts (
	ID int IDENTITY(1, 1) NOT NULL, CONSTRAINT PK_ADMIN_ACCOUNTS_ID PRIMARY KEY CLUSTERED (ID), 
	AdminUsername nvarchar(32) NOT NULL,
	AdminPassword nvarchar(32) NOT NULL,
	AdminID int NOT NULL UNIQUE FOREIGN KEY REFERENCES dbo.Admins(ID)
	);

GO

CREATE TABLE Owner_Accounts (
	ID int IDENTITY(1, 1) NOT NULL, CONSTRAINT PK_OWNER_ACCOUNTS_ID PRIMARY KEY CLUSTERED (ID), 
	OwnerUsername nvarchar(32) NOT NULL,
	OwnerPassword nvarchar(32) NOT NULL,
	OwnerID int NOT NULL UNIQUE FOREIGN KEY REFERENCES dbo.Owners(ID)
	);

GO

CREATE TABLE Agent_Accounts (
	ID int IDENTITY(1, 1) NOT NULL, CONSTRAINT PK_AGENT_ACCOUNTS_ID PRIMARY KEY CLUSTERED (ID), 
	AgentUsername nvarchar(32) NOT NULL,
	AgentPassword nvarchar(32) NOT NULL,
	AgentID int NOT NULL UNIQUE FOREIGN KEY REFERENCES dbo.Agents(ID)
	);

GO

CREATE TABLE Warehouse_Status (
	ID int IDENTITY(1, 1) NOT NULL, CONSTRAINT PK_WAREHOUSE_STATUS_ID PRIMARY KEY CLUSTERED (ID),
	WarehouseStatus nvarchar(30)
	);

GO

CREATE TABLE Warehouse_Types (
	ID int IDENTITY(1, 1) NOT NULL, CONSTRAINT PK_WAREHOUSE_TYPES_ID PRIMARY KEY CLUSTERED (ID),
	WarehouseType nvarchar(30)
	);

GO

CREATE TABLE Warehouses (
	ID int IDENTITY(1, 1) NOT NULL, CONSTRAINT PK_WAREHOUSES_ID PRIMARY KEY CLUSTERED (ID),
	Size float NOT NULL,
	OwnerID int NOT NULL, CONSTRAINT FK_WAREHOUSES_OWNER_ID FOREIGN KEY (OwnerID) REFERENCES dbo.Owners(ID),
	TypeID int NOT NULL, CONSTRAINT FK_WAREHOUSES_TYPE_ID FOREIGN KEY (TypeID) REFERENCES dbo.Warehouse_Types(ID),
	StatusID int NOT NULL, CONSTRAINT FK_WAREHOUSES_STATUS_ID FOREIGN KEY (StatusID) REFERENCES dbo.Warehouse_Status(ID)
	);

GO

CREATE TABLE Climate_Conditions (
	ID int IDENTITY(1, 1) NOT NULL, CONSTRAINT PK_CLIMATE_CONDITIONS_ID PRIMARY KEY CLUSTERED (ID),
	Conditions nvarchar(50) NOT NULL
	);

GO

CREATE TABLE Warehouse_Rooms (
	ID int IDENTITY(1, 1) NOT NULL, CONSTRAINT PK_WAREHOUSE_ROOMS_ID PRIMARY KEY CLUSTERED (ID),
	Size float NOT NULL,
	Price float NOT NULL,
	ClimateConditionsID int NOT NULL, CONSTRAINT FK_ROOMS_CLIMATE_CONDITIONS_ID FOREIGN KEY (ClimateConditionsID) REFERENCES dbo.Climate_Conditions(ID),
	WarehouseID int NOT NULL, CONSTRAINT FK_ROOMS_WAREHOUSE_ID FOREIGN KEY (WarehouseID) REFERENCES dbo.Warehouses(ID)
	);

GO

CREATE TABLE Renter (
	ID int IDENTITY(1, 1) NOT NULL, CONSTRAINT PK_TENENTS_ID PRIMARY KEY CLUSTERED (ID),
	FirsName nvarchar(50) NOT NULL,
	LastName nvarchar(50) NOT NULL,
	PhoneNumber nvarchar(20) NOT NULL
	
	);

CREATE TABLE Warehouse_Contracts (
	ID int IDENTITY(1, 1) NOT NULL, CONSTRAINT PK_WAREHOUSE_CONTRACTS_ID PRIMARY KEY CLUSTERED (ID),
	FromDate date NOT NULL,
	ToDate date NOT NULL,
	Price float NOT NULL,
	WarehouseRoomID int NOT NULL, CONSTRAINT FK_CONTRACTS_WAREHOUS_ROOM_ID FOREIGN KEY (WarehouseRoomID) REFERENCES dbo.Warehouse_Rooms(ID),
	AgentID int NOT NULL, CONSTRAINT FK_CONTRACTS_AGENT_ID FOREIGN KEY (AgentID) REFERENCES dbo.Agents(ID),
	RenterID int NOT NULL, CONSTRAINT FK_CONTRACTS_TENTENT_ID FOREIGN KEY (RenterID) REFERENCES dbo.Renter(ID),
	OwnerID int NOT NULL, CONSTRAINT FK_CONTRACTS_OWNER_ID FOREIGN KEY (OwnerID) REFERENCES dbo.Owners(ID),
	);